application: reading-progress
version: 1
runtime: python
api_version: 1

handlers:
- url: /styles
  static_dir: styles
- url: /js
  static_dir: js
- url: /img
  static_dir: img
- url: /swf
  static_dir: swf
- url: /.*
  script: index.py
